const TCI_SUPABASE_URL='https://pkyjfhecxakkikjhazwq.supabase.co';const TCI_SUPABASE_KEY='sb_publishable_jK5_tytAq8o8lu4hnk7kAg_vMJleuNt';window.tciDb=window.supabase.createClient(TCI_SUPABASE_URL,TCI_SUPABASE_KEY);

async function renderMemberActions(){const host=document.querySelector('[data-member-actions]');if(!host)return;const{data:{session}}=await window.tciDb.auth.getSession();if(!session){host.innerHTML='<a class="btn light" href="/auth?mode=login">Log In</a><a class="btn primary" href="/auth?mode=signup">Sign Up</a>';return}const name=session.user.user_metadata?.display_name||session.user.email?.split('@')[0]||'Member';host.innerHTML=`<a class="memberName" href="/profile">Hi, ${name}</a><a class="btn light" href="/profile/surveys">Survey History</a><button class="btn light" id="logoutBtn">Log Out</button>`;document.getElementById('logoutBtn').onclick=async()=>{await window.tciDb.auth.signOut();location.href='/'}}

function enhanceSiteNavigation(){document.querySelectorAll('.nav').forEach(nav=>{if(!nav.querySelector('a[href="/rankings"]')){const link=document.createElement('a');link.href='/rankings';link.textContent='Rankings';const pollLink=nav.querySelector('a[href="/polls"]');pollLink?.after(link)||nav.append(link)}if(!nav.querySelector('a[href="/surveys"]')){const link=document.createElement('a');link.href='/surveys';link.textContent='Surveys';const rankingLink=nav.querySelector('a[href="/rankings"]');rankingLink?.after(link)||nav.append(link)}});if(location.pathname==='/admin'||location.pathname==='/admin/'){const hero=document.querySelector('.adminHero');if(hero&&!hero.querySelector('[data-admin-modules]')){const actions=document.createElement('div');actions.dataset.adminModules='true';actions.style.display='flex';actions.style.gap='10px';actions.style.flexWrap='wrap';actions.innerHTML='<a class="btn light" href="/">View Public Site</a><a class="btn light" href="/admin/rankings">Manage Rankings</a><a class="btn light" href="/admin/rankings/winners-audit">Winners Audit</a><a class="btn light" href="/admin/qa">QA Dashboard</a><a class="btn light" href="/admin/surveys">Manage Surveys</a><a class="btn light" href="/admin/surveys/responses">Survey Responses</a><a class="btn primary" href="/admin/surveys/results">Survey Reports</a>';const old=hero.querySelector('a.btn[href="/"]');old?.remove();hero.append(actions);const title=hero.querySelector('h1');if(title)title.textContent='Manage Polls, Rankings and Surveys';const copy=hero.querySelector('p');if(copy)copy.textContent='Create, publish, test, rank, and review community polls and structured surveys.'}}if(location.pathname==='/admin/surveys/results'||location.pathname==='/admin/surveys/results/'){const controls=document.querySelector('.reportControls');if(controls&&!controls.querySelector('a[href="/admin/surveys/responses"]')){const link=document.createElement('a');link.className='btn light';link.href='/admin/surveys/responses';link.textContent='Individual Responses';controls.insertBefore(link,controls.lastElementChild)}}if(location.pathname==='/admin/rankings'||location.pathname==='/admin/rankings/'){const wrap=document.querySelector('.wrap');if(wrap&&!wrap.querySelector('a[href="/admin/rankings/winners-audit"]')){const link=document.createElement('a');link.className='btn light';link.href='/admin/rankings/winners-audit';link.textContent='Winners Audit';const status=document.getElementById('status');status?.before(link)}}}

async function enhanceSurveyManagerPreviews(){if(location.pathname!=='/admin/surveys'&&location.pathname!=='/admin/surveys/')return;const{data,error}=await window.tciDb.from('surveys').select('id,slug,status');if(error)return;const surveys=data||[];document.querySelectorAll('.surveyListItem').forEach(item=>{const edit=item.querySelector('a[href^="/admin/surveys/edit?id="]');if(!edit)return;const id=Number(new URL(edit.href).searchParams.get('id'));const survey=surveys.find(x=>x.id===id);const actions=item.querySelector('.surveyListActions');if(!survey||!actions||actions.querySelector(`a[href="/admin/surveys/preview?id=${id}"]`))return;const preview=document.createElement('a');preview.className='btn light';preview.href=`/admin/surveys/preview?id=${id}`;preview.textContent='Preview';actions.insertBefore(preview,actions.children[1]||null)})}

async function enhanceAdminOverview(){if(location.pathname!=='/admin'&&location.pathname!=='/admin/')return;const stats=document.querySelector('.adminStats');if(!stats||stats.querySelector('[data-survey-stat]'))return;const [{data:surveys,error:surveyError},{count:responseCount,error:responseError},{data:periods,error:periodError}]=await Promise.all([window.tciDb.from('surveys').select('id,status'),window.tciDb.from('survey_responses').select('id',{count:'exact',head:true}),window.tciDb.from('ranking_periods').select('id,status')]);if(surveyError||responseError||periodError)return;const surveyList=surveys||[],periodList=periods||[];const surveyCard=document.createElement('article');surveyCard.dataset.surveyStat='true';surveyCard.innerHTML=`<strong>${surveyList.length}</strong><span>Surveys</span>`;const activeCard=document.createElement('article');activeCard.dataset.surveyStat='true';activeCard.innerHTML=`<strong>${surveyList.filter(s=>s.status==='published').length}</strong><span>Published Surveys</span>`;const responseCard=document.createElement('article');responseCard.dataset.surveyStat='true';responseCard.innerHTML=`<strong>${responseCount||0}</strong><span>Survey Responses</span>`;const rankingCard=document.createElement('article');rankingCard.dataset.surveyStat='true';rankingCard.innerHTML=`<strong>${periodList.filter(p=>p.status==='published').length}</strong><span>Published Rankings</span>`;stats.append(surveyCard,activeCard,responseCard,rankingCard);const adminContent=document.getElementById('adminContent');if(adminContent&&!document.querySelector('[data-survey-overview]')){const panel=document.createElement('section');panel.className='adminCard';panel.dataset.surveyOverview='true';panel.style.marginTop='22px';panel.innerHTML='<div class="cardHead"><div><h2>Rankings and Survey Operations</h2><p class="small">Calculate Top 10 standings, run live quality checks, build surveys, and review community responses.</p></div><div class="adminPollActions"><a class="btn light" href="/rankings">Public Rankings</a><a class="btn light" href="/admin/rankings">Manage Rankings</a><a class="btn light" href="/admin/rankings/winners-audit">Winners Audit</a><a class="btn light" href="/admin/qa">QA Dashboard</a><a class="btn light" href="/admin/surveys">Manage Surveys</a><a class="btn primary" href="/admin/surveys/results">Survey Reports</a></div></div>';adminContent.append(panel)}}

const TCI_SITE_URL='https://tcitopvotes.vercel.app';
const TCI_SOCIAL_IMAGE='https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&h=630&q=90';
const TCI_ROUTE_META={
  '/':{title:'TCI Top 10 | Vote, Review and Discover the Best of Turks & Caicos',description:'Community-powered polls and rankings for the best beaches, restaurants, resorts, transportation and experiences in the Turks and Caicos Islands.',type:'website'},
  '/polls':{title:'Community Polls | TCI Top 10',description:'Vote in active Turks and Caicos community polls and follow live results.',type:'website'},
  '/rankings':{title:'Official Rankings | TCI Top 10',description:'Explore published TCI Top 10 rankings selected by local residents and visitors.',type:'website'},
  '/rankings/winners':{title:'Past Winners | TCI Top 10',description:'Browse official first-place winners from published TCI Top 10 ranking periods.',type:'website'},
  '/surveys':{title:'Community Surveys | TCI Top 10',description:'Share feedback through structured community surveys for the Turks and Caicos Islands.',type:'website'}
};
function setMeta(selector,attributes){let node=document.head.querySelector(selector);if(!node){node=document.createElement('meta');document.head.append(node)}Object.entries(attributes).forEach(([key,value])=>node.setAttribute(key,value))}
function setCanonical(url){let link=document.head.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.append(link)}link.href=url}
function cleanPath(){return location.pathname.length>1?location.pathname.replace(/\/$/,''):location.pathname}
function derivePublicMeta(){const path=cleanPath();let meta=TCI_ROUTE_META[path];if(path.startsWith('/polls/')&&path!=='/polls/generic'){const heading=document.getElementById('pollTitle')?.textContent?.trim()||document.querySelector('h1')?.textContent?.trim();const description=document.getElementById('pollDescription')?.textContent?.trim()||'Cast your vote and help the Turks and Caicos community decide.';if(heading&&!/loading|unavailable/i.test(heading))meta={title:`${heading} | TCI Top 10`,description,type:'article'}}if(path.startsWith('/surveys/')){const heading=document.querySelector('h1')?.textContent?.trim();if(heading&&!/loading|unavailable/i.test(heading))meta={title:`${heading} | TCI Top 10`,description:'Complete this TCI Top 10 community survey and share your feedback.',type:'article'}}return meta||{title:document.title||'TCI Top 10',description:'Vote, review and discover the best of the Turks and Caicos Islands.',type:'website'}}
function applySeoMetadata(){const path=cleanPath(),protectedRoute=/^\/(admin|profile|auth)(\/|$)/.test(path);const canonical=TCI_SITE_URL+(path==='/'?'':path);const meta=derivePublicMeta();document.title=meta.title;setMeta('meta[name="description"]',{name:'description',content:meta.description});setMeta('meta[name="robots"]',{name:'robots',content:protectedRoute?'noindex,nofollow':'index,follow,max-image-preview:large'});setMeta('meta[property="og:title"]',{property:'og:title',content:meta.title});setMeta('meta[property="og:description"]',{property:'og:description',content:meta.description});setMeta('meta[property="og:type"]',{property:'og:type',content:meta.type});setMeta('meta[property="og:url"]',{property:'og:url',content:canonical});setMeta('meta[property="og:site_name"]',{property:'og:site_name',content:'TCI Top 10'});setMeta('meta[property="og:image"]',{property:'og:image',content:TCI_SOCIAL_IMAGE});setMeta('meta[name="twitter:card"]',{name:'twitter:card',content:'summary_large_image'});setMeta('meta[name="twitter:title"]',{name:'twitter:title',content:meta.title});setMeta('meta[name="twitter:description"]',{name:'twitter:description',content:meta.description});setMeta('meta[name="twitter:image"]',{name:'twitter:image',content:TCI_SOCIAL_IMAGE});setCanonical(canonical);let schema=document.getElementById('tciStructuredData');if(schema)schema.remove();schema=document.createElement('script');schema.type='application/ld+json';schema.id='tciStructuredData';schema.textContent=JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':TCI_SITE_URL+'/#organization',name:'TCI Top 10',url:TCI_SITE_URL,description:'Community-powered voting and rankings for the Turks and Caicos Islands.'},{'@type':'WebSite','@id':TCI_SITE_URL+'/#website',url:TCI_SITE_URL,name:'TCI Top 10',publisher:{'@id':TCI_SITE_URL+'/#organization'},potentialAction:{'@type':'SearchAction',target:TCI_SITE_URL+'/polls?q={search_term_string}','query-input':'required name=search_term_string'}},{'@type':'WebPage','@id':canonical+'#webpage',url:canonical,name:meta.title,description:meta.description,isPartOf:{'@id':TCI_SITE_URL+'/#website'}}]});document.head.append(schema)}
async function recordShare(channel){try{const path=cleanPath();const slug=path.split('/').filter(Boolean).pop()||null;const type=path.startsWith('/polls/')?'poll':path.startsWith('/surveys/')?'survey':path.startsWith('/rankings')?'ranking':'page';const{data:{session}}=await window.tciDb.auth.getSession();await window.tciDb.from('share_events').insert({page_path:path,content_type:type,content_slug:slug,share_channel:channel,user_id:session?.user?.id||null})}catch(_){}}
function addShareControl(){const path=cleanPath();if(/^\/(admin|profile|auth)(\/|$)/.test(path)||document.querySelector('[data-share-page]'))return;const host=document.querySelector('.hero,.pollHero,.directoryHero,.surveyHero,main .wrap .hero');if(!host)return;const button=document.createElement('button');button.type='button';button.className='btn light';button.dataset.sharePage='true';button.textContent='Share';button.style.marginTop='14px';button.onclick=async()=>{const meta=derivePublicMeta(),url=location.href;try{if(navigator.share){await navigator.share({title:meta.title,text:meta.description,url});await recordShare('native')}else{await navigator.clipboard.writeText(url);button.textContent='Link Copied';await recordShare('clipboard');setTimeout(()=>button.textContent='Share',1800)}}catch(error){if(error?.name!=='AbortError')button.textContent='Unable to Share'}};host.append(button)}

window.addEventListener('DOMContentLoaded',()=>{renderMemberActions();enhanceSiteNavigation();applySeoMetadata();addShareControl();setTimeout(()=>{applySeoMetadata();addShareControl()},1200);setTimeout(enhanceAdminOverview,300);setTimeout(enhanceSurveyManagerPreviews,500)});window.tciDb.auth.onAuthStateChange(()=>renderMemberActions());