(()=>{
  const db=()=>window.tciDb;
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  let periods=[],polls=[],activePollId=null,timeframe='monthly',audience='overall',referenceDate=new Date().toISOString().slice(0,10),currentRows=[],historyRows=[];

  function addStyles(){if(document.getElementById('rankingsV2Styles'))return;const style=document.createElement('style');style.id='rankingsV2Styles';style.textContent=`
  .v2Controls{display:grid;grid-template-columns:1fr auto;gap:12px;margin:18px 0}.v2Select{min-height:48px;padding:12px 14px;border:1px solid #dce5ef;border-radius:12px;background:#fff}.v2Tabs{display:flex;gap:7px;padding:5px;background:#eaf1f8;border-radius:14px;overflow:auto}.v2Tab{border:0;border-radius:10px;padding:10px 13px;background:transparent;color:#31506f;font-weight:850;white-space:nowrap}.v2Tab.active{background:#fff;color:#1477e6;box-shadow:0 4px 14px rgba(7,27,52,.08)}.v2Panel{background:#fff;border:1px solid #e6edf5;border-radius:20px;padding:18px;margin-top:16px}.v2Stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.v2Stat{background:#fff;border:1px solid #e6edf5;border-radius:16px;padding:15px}.v2Stat strong{display:block;font-size:27px;color:#1477e6}.v2Grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.v2Rank{display:grid;grid-template-columns:52px 1fr auto;gap:14px;align-items:center;background:#fff;border:1px solid #e6edf5;border-radius:17px;padding:15px;margin:10px 0}.v2Position{font-size:28px;font-weight:950;color:#1477e6}.v2Pct{display:inline-flex;padding:4px 9px;border-radius:999px;background:#eaf3ff;color:#1477e6;font-weight:900}.v2Label{font-size:11px;font-weight:900;letter-spacing:.05em;color:#62748a}.v2Empty{text-align:center;padding:28px 18px;background:#fff;border:1px solid #e6edf5;border-radius:20px}.v2Chart{width:100%;height:250px;display:block}.v2Legend{display:flex;gap:10px;flex-wrap:wrap;margin-top:10px}.v2Legend span{font-size:12px;font-weight:800}.v2Mini{padding:12px;border-radius:14px;background:#f7f9fc;border:1px solid #e6edf5;margin-top:8px}.v2Note{font-size:12px;color:#62748a;margin-top:8px}@media(max-width:760px){.v2Controls{grid-template-columns:1fr}.v2Stats{grid-template-columns:1fr 1fr}.v2Grid{grid-template-columns:1fr}.v2Rank{grid-template-columns:42px 1fr}.v2Rank>div:last-child{grid-column:2}.v2Chart{height:210px}}
  `;document.head.append(style)}

  function buildShell(){const main=document.querySelector('main.wrap');if(!main||main.dataset.v2Ready)return false;main.dataset.v2Ready='true';[...main.children].slice(1).forEach(node=>node.remove());main.insertAdjacentHTML('beforeend',`
    <div class="v2Controls"><select id="v2Poll" class="v2Select" aria-label="Ranking poll"></select><a class="btn light" href="/rankings/winners">Past Winners</a></div>
    <div class="v2Tabs" id="timeframeTabs"><button class="v2Tab active" data-timeframe="monthly">Monthly</button><button class="v2Tab" data-timeframe="yearly">Yearly</button><button class="v2Tab" data-timeframe="all_time">All-Time</button></div>
    <div class="v2Tabs" id="audienceTabsV2" style="margin-top:10px"><button class="v2Tab active" data-audience="overall">Overall</button><button class="v2Tab" data-audience="locals">Locals’ Choice</button><button class="v2Tab" data-audience="visitors">Visitors’ Choice</button></div>
    <div class="v2Stats"><article class="v2Stat"><strong id="statSelections">0</strong><span>Selections</span></article><article class="v2Stat"><strong id="statOptions">0</strong><span>Ranked Options</span></article><article class="v2Stat"><strong id="statPeriods">0</strong><span>Published Periods</span></article><article class="v2Stat"><strong id="statLeader">—</strong><span>Current Leader</span></article></div>
    <p id="v2Status" class="small">Loading published rankings...</p><section id="v2RankingList"></section>
    <div class="v2Grid"><section class="v2Panel"><h2>Trending</h2><p class="small">Options showing the strongest recent published movement.</p><div id="v2Trending"></div></section><section class="v2Panel"><h2>Hidden Gems</h2><p class="small">Strong performers outside the top three, based on published results.</p><div id="v2Hidden"></div></section></div>
    <section class="v2Panel"><div class="sectionTitle"><div><h2>Ranking History</h2><p class="small">Published position history for the selected poll.</p></div><select id="historyOption" class="v2Select" aria-label="History option"></select></div><div id="v2Chart"></div><p class="v2Note">Charts use published ranking periods only. A lower position number is better.</p></section>
  `);return true}

  async function loadPublishedPeriods(){const{data,error}=await db().from('ranking_periods').select('id,poll_id,title,period_key,published_at,polls(title)').eq('status','published').order('published_at',{ascending:false});if(error)throw error;periods=data||[];polls=[...new Map(periods.map(p=>[p.poll_id,{id:p.poll_id,title:p.polls?.title||'Ranking'}])).values()];const select=document.getElementById('v2Poll');select.innerHTML=polls.length?polls.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join(''):'<option value="">No published rankings</option>';select.disabled=!polls.length;activePollId=polls[0]?.id||null;select.onchange=()=>{activePollId=Number(select.value)||null;loadAll()};document.getElementById('statPeriods').textContent=periods.length}

  async function loadRanking(){const status=document.getElementById('v2Status'),host=document.getElementById('v2RankingList');if(!activePollId){status.textContent='';host.innerHTML='<div class="v2Empty"><h2>No published rankings yet</h2><p>The current period must be reviewed and published before Version 2 statistics appear.</p><a class="btn primary" href="/polls">Explore Active Polls</a></div>';updatePanels();return}status.textContent='Loading ranking view...';const{data,error}=await db().rpc('get_published_timeframe_ranking',{target_poll_id:activePollId,target_timeframe:timeframe,target_audience:audience,target_reference_date:referenceDate});if(error){status.textContent='Unable to load this ranking view.';host.innerHTML='';return}currentRows=data||[];const total=Number(currentRows[0]?.total_votes||0);document.getElementById('statSelections').textContent=total.toLocaleString();document.getElementById('statOptions').textContent=currentRows.length;document.getElementById('statLeader').textContent=total?currentRows[0]?.option_label||'—':'—';if(!total){status.textContent='';host.innerHTML=`<div class="v2Empty"><h2>No published ${timeframe.replace('_','-')} data</h2><p>This view will populate after eligible ${audience==='locals'?'local resident':audience==='visitors'?'visitor':'community'} votes are included in a published ranking period.</p></div>`;updatePanels();return}status.textContent=`${label(timeframe)} · ${label(audience)} · ${total.toLocaleString()} total selection${total===1?'':'s'}.`;host.innerHTML=currentRows.map(row=>`<article class="v2Rank"><div class="v2Position">${row.ranking_position}</div><div><h2>${esc(row.option_label)}${row.is_tied?' <span class="tie">TIED</span>':''}</h2><div><span class="v2Pct">${Number(row.vote_percentage).toFixed(1)}%</span> <span class="small">${Number(row.vote_count)} vote${Number(row.vote_count)===1?'':'s'}</span></div></div><div class="v2Label">${label(audience).toUpperCase()}</div></article>`).join('');updatePanels()}

  async function loadHistory(){if(!activePollId){historyRows=[];renderHistory();return}const{data}=await db().rpc('get_ranking_history',{target_poll_id:activePollId,target_option_id:null});historyRows=data||[];const options=[...new Map(historyRows.map(r=>[r.option_id,r.option_label])).entries()];const select=document.getElementById('historyOption');select.innerHTML=options.length?'<option value="">All options</option>'+options.map(([id,name])=>`<option value="${id}">${esc(name)}</option>`).join(''):'<option value="">No published history</option>';select.disabled=!options.length;select.onchange=renderHistory;renderHistory()}

  function renderHistory(){const host=document.getElementById('v2Chart'),selected=Number(document.getElementById('historyOption')?.value)||null,rows=selected?historyRows.filter(r=>r.option_id===selected):historyRows;if(!rows.length){host.innerHTML='<div class="v2Empty"><p>No published history is available yet.</p></div>';return}const periods=[...new Map(rows.map(r=>[r.period_id,{id:r.period_id,title:r.period_title,date:r.published_at}])).values()];const options=[...new Map(rows.map(r=>[r.option_id,r.option_label])).entries()].slice(0,5);const width=800,height=250,pad=34,maxPos=Math.max(10,...rows.map(r=>Number(r.ranking_position)));const x=i=>periods.length===1?width/2:pad+i*(width-2*pad)/(periods.length-1);const y=pos=>pad+(Number(pos)-1)*(height-2*pad)/Math.max(1,maxPos-1);let svg=`<svg class="v2Chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Ranking history chart">`;for(let p=1;p<=maxPos;p++){svg+=`<line x1="${pad}" y1="${y(p)}" x2="${width-pad}" y2="${y(p)}" stroke="#e6edf5"/><text x="8" y="${y(p)+4}" font-size="11" fill="#62748a">#${p}</text>`}options.forEach(([id,name],index)=>{const series=periods.map((period,i)=>{const row=rows.find(r=>r.period_id===period.id&&r.option_id===id);return row?`${x(i)},${y(row.ranking_position)}`:null}).filter(Boolean);if(series.length)svg+=`<polyline points="${series.join(' ')}" fill="none" stroke="hsl(${(index*72+205)%360} 65% 45%)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>`});svg+='</svg>';host.innerHTML=svg+`<div class="v2Legend">${options.map(([id,name],i)=>`<span style="color:hsl(${(i*72+205)%360} 65% 38%)">● ${esc(name)}</span>`).join('')}</div>`}

  function updatePanels(){const trending=document.getElementById('v2Trending'),hidden=document.getElementById('v2Hidden');if(!currentRows.length||!Number(currentRows[0]?.total_votes)){trending.innerHTML=hidden.innerHTML='<div class="v2Mini small">Available after published ranking data exists.</div>';return}const histLatest=historyRows.filter(r=>r.period_id===Math.max(...historyRows.map(x=>Number(x.period_id)||0)));const trend=histLatest.filter(r=>r.movement==='up').sort((a,b)=>(a.ranking_position-b.ranking_position)).slice(0,3);trending.innerHTML=trend.length?trend.map(r=>`<div class="v2Mini"><strong>▲ ${esc(r.option_label)}</strong><div class="small">Now #${r.ranking_position} · ${r.vote_count} votes</div></div>`).join(''):'<div class="v2Mini small">No upward movement in the latest published period.</div>';const gems=currentRows.filter(r=>Number(r.ranking_position)>3&&Number(r.vote_percentage)>=10).slice(0,3);hidden.innerHTML=gems.length?gems.map(r=>`<div class="v2Mini"><strong>${esc(r.option_label)}</strong><div class="small">#${r.ranking_position} · ${Number(r.vote_percentage).toFixed(1)}% of selections</div></div>`).join(''):'<div class="v2Mini small">No Hidden Gems meet the current published-data threshold.</div>'}

  function label(value){return value==='all_time'?'All-Time':value==='yearly'?'Yearly':value==='monthly'?'Monthly':value==='locals'?'Locals’ Choice':value==='visitors'?'Visitors’ Choice':'Overall'}
  function wireTabs(){document.querySelectorAll('[data-timeframe]').forEach(btn=>btn.onclick=()=>{timeframe=btn.dataset.timeframe;document.querySelectorAll('[data-timeframe]').forEach(x=>x.classList.toggle('active',x===btn));loadRanking()});document.querySelectorAll('[data-audience]').forEach(btn=>btn.onclick=()=>{audience=btn.dataset.audience;document.querySelectorAll('[data-audience]').forEach(x=>x.classList.toggle('active',x===btn));loadRanking()})}
  async function loadAll(){await Promise.all([loadRanking(),loadHistory()]);updatePanels()}
  async function start(){if(location.pathname!=='/rankings'&&location.pathname!=='/rankings/')return;addStyles();if(!buildShell())return;wireTabs();try{await loadPublishedPeriods();await loadAll()}catch(error){document.getElementById('v2Status').textContent='Unable to load Version 2 rankings.'}}
  if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',()=>setTimeout(start,250),{once:true});else setTimeout(start,250);
})();